### ISSUE TITLE
Inconsistent order in references

### ISSUE THREAD

**Issue by rasmus-bn** [HazemSaeid/UFOEXAM#2]
At the end of the blog you have a references section but not all references are included. Some references are just linked directly in the blog text. As a reader it can be confusing to read your source since they aren't ordered in a consistent way throughout the blog.

I would suggest that you have all links listed in the end, like you have already partly done. Then if you want to reference a source you could maybe provide the number of that source like this<sup>source</sup>.

**Comment by HazemSaeid** [comment]
References fixed
