### ISSUE TITLE
Headings

### ISSUE THREAD

**Issue by rasmus-bn** [HazemSaeid/UFOEXAM#3]
So this is only related to formatting.

In some of the headings there are strange numbers. It seems like you wanted to add numbering to the headings but the numbers aren't really consistent so it looks a bit messy.

<h1>Evidence from our project<sup>3</sup> <g-emoji class="g-emoji" alias="mag" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f50d.png">🔍</g-emoji></h1>

*Subjective note*: Also I would personally hold back on the emojis on the headings. They are good at making the blog more appealing but at some point it lowers the seriousness of the blog. Especially the "!?" seems a bit click-baity to me. However this is just my own personal opinion.

**Comment by HazemSaeid** [comment]
Fixed headings, 
I understand the confusion. References are now being referenced in the paragraph sections.
