### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by rasmus-bn** [HazemSaeid/UFOEXAM#4]
| Technical Dimensions / Weight                                | Does Not Meet Expectations (1-3 points)                                                         | Meets Expectations (4-7 points)                                                                             | Exceeds Expectations (8-10 points)                                                                                                          | Score | Weighted | Notes |
|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|-------|----------|-------|
| **Overview 30%**                                             | Fails to provide an overview and define the scope of the work                                   | Provides an adequate overview and general explanation on the scope of the work                              | Provides a thorough overview and thoroughly defines the scope of the work                                                                   |   9   |   2.7/3  | You could mention in the abstract that you performed an experiment. Also see issue #3 |
| **Reliable Data from Credible Sources 10%**                  | Data not reliable and fails to provide reference to source of data                              | Adequately describes selection of data and provides a general explanation on source ofdata                  | Provides in-depth explanations on data selection and credible sources with clear and complete references                                    |   3   |   0.3/1  | Look at issue #1 & #2. I could not give you higher than 3 because of issue #1 |
| **Design Constraints and Assumptions 15%**                   | Fails to discuss design constraints and alternatives; provides no justification for assumptions | Adequately explains and justifies the design constraints, design alternatives and assumptions used          | In-depth explanations and justifications are provided on design constraints, alternatives and assumptions used                              |  10   | 1.5/1.5  | Nice |
| **Theoretical Explanations 20%**                             | Fails to adequately cover theoretical explanations                                              | Adequately addresses theoretical explanations                                                               | Demonstrates in-depth research and analysis                                                                                                 |  10   |     2/2  | It is as in-depth as it can be in such a short blog |
| **Design Criteria, Sample Calculations and Simulations 20%** | Fails to provide appropriate design methodology, relevant sample calculations, and simulations  | Demonstrates adequate level of design criteria and relevant sample calculations and appropriate simulations | Provides in-depth explanations on design criteria, thoroughly discusses all required calculation steps and uses simulations where necessary |  10   |     2/2  | Same as above. Nice that you showed screenshots from your experiment |
| **Previous Work / Future Work 5%**                           | Fails to summarize previous work or to discuss future work                                      | Adequately summarizes previous work and discusses potential future work                                     | Provides a thorough summary of previous workand proposes and discusses future work in detail                                                |  10   | 0.5/0.5  | You show as much code as is relevant in the scope of the blog. |
| **Total 100%**                                               |                                                                                                 | **Technical / Content Criteria**                                                                            |                                                                                                                                             |  52   |    9/10  ||

**Comment by HazemSaeid** [comment]
Fixed the issues mentioned in the evaluation scheme
